apiVersion: apps/vi
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      comoponent: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: jrayback/multi-server
          ports:
            - containerPort: 5000